title: Rishi Mullur
author: Rishi Mullur
email: rishirm@uw.com
description: 
url: "https://rishim.xyz"
favicon: favicon.ico
# show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
remote_theme: rmullur/minmax
plugins:
  - jekyll-feed

moving:
  about_you:  currently pursuing a graduate program in Technology Innovation at the university of washington. previously been a programmer, a product manager and a entrepreneur. Usually found reading one of the many pending books from my bookshelf. 
  
  
  you can find my writings <a href="https://haecceity.substack.com/">here</a>.   
  avatar_url: IMG_0004.JPG
  date_format: "%b %d"
  back_to: "Home"
  social_links:
    linkedin: rishimullur
    twitter: rishimullur
