title: Rishi Mullur
author: Rishi Mullur
email: rishirm@uw.com
description: 
url: "https://rishim.xyz"
# show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
remote_theme: rmullur/minmax
plugins:
  - jekyll-feed

moving:
  about_you: creating my own <a href="https://maggieappleton.com/garden-history">digital garden</a>. building and breaking things. currently pursuing a masters program at the university of washington. you can find my writings <a href="https://haecceity.substack.com/">here</a>.   
  avatar_url: IMG_0004.JPG
  date_format: "%b %d"
  back_to: "Home"
  social_links:
    linkedin: rishimullur
