title: Rishi Mullur
author: Rishi Mullur
# email: rishirm@uw.com
description: Building my own" (h/t <a href="https://maggieappleton.com/garden-history">digital garden</a>). More about me <a href="https://rishim.xyz/about">here</a>.
url: "https://rishim.xyz/"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: building and breaking things. currently pursuing a masters program at the university of washington.
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    linkedin: rishimullur
