title: Rishi's Blog
author: Rishi Mullur
email: rishirm@uw.com
description: A digital garden
url: "https://rishim.xyz/"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: building and breaking things.
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    linkedin: rishimullur
