title: Rishi Mullur
author: Rishi Mullur
# email: rishirm@uw.com
description: Building my own (h/t <a href="https://maggieappleton.com/garden-history">digital garden</a>). More about me <a href="https://rishim.xyz/about>here</a>.
url: "https://rishim.xyz"
show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
remote_theme: rmullur/minmax
plugins:
  - jekyll-feed

moving:
  about_you: building and breaking things. currently pursuing a masters program at the university of washington.
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Home"
  social_links:
    linkedin: rishimullur
